In [2]:
import numpy as np

In [3]:
ratings = np.array([
    [4,7,8,10],
    [3,9,10,3],
    [3,9,10,10]
])
ratings

array([[ 4,  7,  8, 10],
       [ 3,  9, 10,  3],
       [ 3,  9, 10, 10]])

In [4]:
ratings.shape

(3, 4)

In [11]:
avgratingofmovie = np.mean(ratings,axis=0)
avgratingofmovie

array([3.33333333, 8.33333333, 9.33333333, 7.66666667])

In [25]:
highratingmovie = np.argmax(avgratingofmovie)
highratingmovie

np.int64(2)

In [10]:
avgratingbyuser = np.mean(ratings,axis=1)
avgratingbyuser

array([7.25, 6.25, 8.  ])

In [13]:
userhighrating = np.argmax(avgratingbyuser)
userhighrating

np.int64(2)

In [17]:
highratedmovies = ratings >= 8
highratedmovies
ratingsofhighratedmovies = ratings[highratedmovies]

In [18]:
print("ratings of the movies rated high ",ratingsofhighratedmovies)

ratings of the movies rated high  [ 8 10  9 10  9 10 10]


In [20]:
total = len(ratingsofhighratedmovies)
print("total no of high rated movies",total)

total no of high rated movies 7


In [22]:
minimumrating = np.min(ratings)
print("minimum rating acrooss the ratings ",minimumrating)

minimum rating acrooss the ratings  3


In [23]:
maximumrating = np.max(ratings)
print("maximum rating across the ratings",maximumrating)

maximum rating across the ratings 10


In [26]:
normalizedratings = (ratings-minimumrating)/(maximumrating-minimumrating)
normalizedratings
print(np.round(normalizedratings,2))

[[0.14 0.57 0.71 1.  ]
 [0.   0.86 1.   0.  ]
 [0.   0.86 1.   1.  ]]


In [27]:
print("The highest rated movie is " , np.argmax(avgratingofmovie))

The highest rated movie is  2


In [28]:
print("the lowest rated movie is " , np.argmin(avgratingofmovie))

the lowest rated movie is  0


In [37]:
print("movies with the avg rating >= 8" , avgratingofmovie[avgratingofmovie >= 8])

movies with the avg rating >= 8 [8.33333333 9.33333333]


In [40]:
sorted_indices = np.argsort(avgratingofmovie)
top_2 = sorted_indices[2:4]
print("the top 2 perforing movies" , top_2)

the top 2 perforing movies [1 2]
