In [31]:
import numpy as np

In [32]:
students = np.array(["nikita","javid","yuvraj","kirti","sanik","tulip","kartik","owl"])

In [33]:
student_data = np.array([
    [6,78,98],
    [2,65,99],
    [3,34,65],
    [7,34,98],
    [8,67,87],
    [9,23,76],
    [4,14,76],
    [10,76,98]
])

In [34]:
actual_scores = np.array ([98,96,93,94,95,99,100,23])

In [35]:
weights = np.array([1.5,0.3,0.6])

In [36]:
column_min = np.min(student_data,axis = 0)
column_max = np.max(student_data,axis = 0)
normalized_data = (student_data - column_min)/(column_max-column_min)
print("The normalised data values are\n", normalized_data)

The normalised data values are
 [[0.5        1.         0.97058824]
 [0.         0.796875   1.        ]
 [0.125      0.3125     0.        ]
 [0.625      0.3125     0.97058824]
 [0.75       0.828125   0.64705882]
 [0.875      0.140625   0.32352941]
 [0.25       0.         0.32352941]
 [1.         0.96875    0.97058824]]


In [37]:
raw_predicted_scores = student_data@weights
print("Raw predicted scores",raw_predicted_scores)

Raw predicted scores [91.2 81.9 53.7 79.5 84.3 66.  55.8 96.6]


In [38]:
normalized_predicted_scores = normalized_data@weights
print(" Normalized predicted scores are ",normalized_predicted_scores)

 Normalized predicted scores are  [1.63235294 0.8390625  0.28125    1.61360294 1.76167279 1.54880515
 0.56911765 2.37297794]


In [39]:
Raw_error = actual_scores - raw_predicted_scores
print("Raw errors",Raw_error)

Raw errors [  6.8  14.1  39.3  14.5  10.7  33.   44.2 -73.6]


In [40]:
normalized_Raw_error = actual_scores - normalized_predicted_scores
print("Normalized Raw errors",normalized_Raw_error)

Normalized Raw errors [96.36764706 95.1609375  92.71875    92.38639706 93.23832721 97.45119485
 99.43088235 20.62702206]


In [41]:
normalized_abs_error = np.abs(normalized_Raw_error)
print("NOrmalized absolute error" , normalized_abs_error)

NOrmalized absolute error [96.36764706 95.1609375  92.71875    92.38639706 93.23832721 97.45119485
 99.43088235 20.62702206]


In [42]:
abs_error = np.abs(Raw_error)
print("Absolute eroors " ,abs_error)

Absolute eroors  [ 6.8 14.1 39.3 14.5 10.7 33.  44.2 73.6]


In [43]:
raw_avg_error = np.mean(abs_error)
print("avg error across the whole calculation ", raw_avg_error)

avg error across the whole calculation  29.525000000000002


In [44]:
normalized_avg_error = np.mean(normalized_abs_error)
print("normalized avg error across the whole calculation ", normalized_avg_error)

normalized avg error across the whole calculation  85.9226447610294


In [45]:
best_indx = np.argmin(abs_error)
print("the closest prediction was",students[best_indx],"Actual score",actual_scores[best_indx],"Predicted score",raw_predicted_scores[best_indx],"Absolute error" ,abs_error[best_indx])

the closest prediction was nikita Actual score 98 Predicted score 91.2 Absolute error 6.799999999999997


In [46]:
normalised_best_indx = np.argmin(normalized_abs_error)
print("the closest prediction was",students[best_indx],"Actual score",actual_scores[best_indx],"Predicted score",normalized_predicted_scores[best_indx],"Absolute error" ,normalized_abs_error[best_indx])

the closest prediction was nikita Actual score 98 Predicted score 1.6323529411764706 Absolute error 96.36764705882354


In [47]:
worst_indx = np.argmax(abs_error)
print("the farthest prediction was",students[worst_indx],"Actual score",actual_scores[worst_indx],"Predicted score",raw_predicted_scores[worst_indx],"Absolute error" ,abs_error[worst_indx])

the farthest prediction was owl Actual score 23 Predicted score 96.6 Absolute error 73.6


In [48]:
normalized_worst_indx = np.argmax(normalized_abs_error)
print("the farthest prediction was",students[normalized_worst_indx],"Actual score",actual_scores[normalized_worst_indx],"Predicted score",normalized_predicted_scores[normalized_worst_indx],"Absolute error" ,abs_error[normalized_worst_indx])

the farthest prediction was kartik Actual score 100 Predicted score 0.5691176470588235 Absolute error 44.2


In [49]:
categorize = np.where(normalized_predicted_scores>=80,"High",np.where(normalized_predicted_scores >= 60 , "average" , "low"))
for name,score,cat in zip (students,normalized_predicted_scores,categorize):
  print(f"{name}:{score:.2f}:{cat}")

nikita:1.63:low
javid:0.84:low
yuvraj:0.28:low
kirti:1.61:low
sanik:1.76:low
tulip:1.55:low
kartik:0.57:low
owl:2.37:low


In [50]:
categorize = np.where(raw_predicted_scores>=80,"High",np.where(raw_predicted_scores >= 60 , "average" , "low"))
for name,score,cat in zip (students,raw_predicted_scores,categorize):
  print(f"{name}:{score:.2f}:{cat}")

nikita:91.20:High
javid:81.90:High
yuvraj:53.70:low
kirti:79.50:average
sanik:84.30:High
tulip:66.00:average
kartik:55.80:low
owl:96.60:High


In [51]:
avg_actual_score = np.mean(actual_scores)
avg_raw_predicted_score = np.mean(raw_predicted_scores)
if avg_raw_predicted_score > avg_actual_score:
  print("THE MODEL IS HYPING A LOT ")
else:
  print("THE MODEL IS UNDERHYPING A LOT")

THE MODEL IS UNDERHYPING A LOT


In [52]:
avg_actual_score = np.mean(actual_scores)
avg_normalized_predicted_score = np.mean(normalized_predicted_scores)
if avg_normalized_predicted_score > avg_actual_score:
  print("THE MODEL IS HYPING A LOT ")
else:
  print("THE MODEL IS UNDERHYPING A LOT")

THE MODEL IS UNDERHYPING A LOT


In [53]:
print("the avg predicted scores are :",avg_raw_predicted_score)
print("the avg normalised predicted scores are :",avg_normalized_predicted_score)
print("the avg actual scores are :",avg_actual_score)
print("MAE",raw_avg_error)

the avg predicted scores are : 76.125
the avg normalised predicted scores are : 1.3273552389705883
the avg actual scores are : 87.25
MAE 29.525000000000002


In [54]:
study_hour_min = np.min(normalized_data[:,0:1],axis=0)
print("the min hours of study are",study_hour_min)

the min hours of study are [0.]


In [55]:
high_count = np.sum(normalized_predicted_scores >= 80)
low_count = np.sum(normalized_predicted_scores < 60)

In [56]:
total = len(students)
high_pct = (np.sum(categorize == "High") / total) * 100
avg_pct = (np.sum(categorize == "average") / total) * 100
low_pct = (np.sum(categorize == "low") / total) * 100

In [57]:
improvement = abs_error - normalized_abs_error
most_improved_idx = np.argmax(improvement)
print("Most improved student:", students[most_improved_idx])

Most improved student: owl


In [58]:
print(f"Most improved student after normalization: {students[most_improved_idx]} (Error reduced by {improvement[most_improved_idx]:.2f})")

Most improved student after normalization: owl (Error reduced by 52.97)


In [59]:
print(f"Students with predicted score >= 80: {high_count}")
print(f"Students with predicted score < 60: {low_count}")

Students with predicted score >= 80: 0
Students with predicted score < 60: 8


In [60]:
print(f"Category Distribution: High={high_pct:.1f}%, Average={avg_pct:.1f}%, Low={low_pct:.1f}%")

Category Distribution: High=50.0%, Average=25.0%, Low=25.0%
