In [2]:
import numpy as np

In [5]:
fitness_data = np.array([
    [8000,2200,45],
    [12000,2800,60],
    [4500,1600,20],
    [10500,2500,50],
    [3000,1400,15]
])
fitness_data

array([[ 8000,  2200,    45],
       [12000,  2800,    60],
       [ 4500,  1600,    20],
       [10500,  2500,    50],
       [ 3000,  1400,    15]])

In [6]:
fitness_data.shape

(5, 3)

In [9]:
avgmetrics = np.mean(fitness_data,axis=0)
avgmetrics

array([7600., 2100.,   38.])

In [12]:
high_step_mask = fitness_data[:,0] > 8000
high_step_mask

array([False,  True, False,  True, False])

In [14]:
activity_status = np.where(fitness_data[:,0] >= 2000 , "Active" , "Rest" )
activity_status

array(['Active', 'Active', 'Rest', 'Active', 'Rest'], dtype='<U6')

In [18]:
minsteps = np.min(fitness_data[:,0])
minsteps

np.int64(3000)

In [20]:
mincalorieburned = np.min(fitness_data[:,1])
mincalorieburned

np.int64(1400)

In [21]:
minactiveness =  np.min(fitness_data[:,2])
minactiveness

np.int64(15)

In [22]:
metricmin = np.min(fitness_data)
metricmin

np.int64(15)

In [23]:
metricmax = np.max(fitness_data)
metricmax

np.int64(12000)

In [24]:
scaled_data = (fitness_data - metricmin)/(metricmax-metricmin)
scaled_data

array([[6.66249479e-01, 1.82311222e-01, 2.50312891e-03],
       [1.00000000e+00, 2.32373801e-01, 3.75469337e-03],
       [3.74217772e-01, 1.32248644e-01, 4.17188152e-04],
       [8.74843554e-01, 2.07342511e-01, 2.92031706e-03],
       [2.49061327e-01, 1.15561118e-01, 0.00000000e+00]])

In [25]:
highstep_day = np.argmax(fitness_data[:,0])
highstep_day

np.int64(1)

In [26]:
lowest_sleep_day = np.argmin(fitness_data[:,2])
lowest_sleep_day

np.int64(4)