In [48]:
import numpy as np

In [66]:
sales = np.array([
    [10, 12, 15],
    [20, 18, 22],
    [8, 9, 11],
    [14, 15, 17]
])
print(sales)

[[10 12 15]
 [20 18 22]
 [ 8  9 11]
 [14 15 17]]


In [67]:
print("dimension of the arrays",sales.ndim)

2


In [68]:
print("shape of the arrays ",sales.shape)

(4, 3)


In [69]:
print("total sales across the stores",np.sum(sales,axis=1))

total sales across the stores [37 60 28 46]


In [70]:
print("total sales across the months ",np.sum(sales,axis=0))

total sales across the months  [52 54 65]


In [72]:
print("sales of the store 1",sales[0])

sales of the store 1 [10 12 15]


In [73]:
print("sales of the second month",sales[:,1])

sales of the second month [12 18  9 15]


In [74]:
print("sales of the store 2 in third month",sales[1,2])

sales of the store 2 in third month 22


In [82]:
store_total = np.sum(sales,axis = 1 )
best_store = np.argmax(store_total)
month_total = np.sum(sales,axis = 0 )
maxmonth = np.argmax(month_total)


In [84]:
print("best performing store", best_store)
print("best-performing month across all stores ", maxmonth)

best performing store 1
best-performing month across all stores  2


In [81]:
updated_sales = np.clip(sales*1.10,a_min=0,a_max=20)
updated_sales


array([[11. , 13.2, 16.5],
       [20. , 19.8, 20. ],
       [ 8.8,  9.9, 12.1],
       [15.4, 16.5, 18.7]])