In [2]:
import numpy as np

In [4]:
expense_data = np.array([
    [23,443,384],
    [73,94,934],
    [67,4903,4390],
    [783,4,43],
    [83,409,93],
    [3,442,23],
    [33,43,23]
])
expense_data

array([[  23,  443,  384],
       [  73,   94,  934],
       [  67, 4903, 4390],
       [ 783,    4,   43],
       [  83,  409,   93],
       [   3,  442,   23],
       [  33,   43,   23]])

In [6]:
total_spent = np.sum(expense_data)
total_spent

np.int64(13293)

In [7]:
category_totals = np.sum(expense_data,axis=0)
category_totals

array([1065, 6338, 5890])

In [9]:
daily_totals = np.sum(expense_data,axis=1)
daily_totals

array([ 850, 1101, 9360,  830,  585,  468,   99])

In [35]:
expensive_days = np.where(daily_totals>= 500)
expensive_days

(array([0, 1, 2, 3, 4]),)

In [11]:
print("total weekly expenditure",total_spent)

total weekly expenditure 13293


In [12]:
print("total category wise spent " , category_totals)

total category wise spent  [1065 6338 5890]


In [13]:
print("Daily total spent",daily_totals)

Daily total spent [ 850 1101 9360  830  585  468   99]


In [41]:
print("days with spending high",expensive_days)

days with spending high (array([0, 1, 2, 3, 4]),)


In [16]:
highest_food_expense = np.max(expense_data[:,0])
highest_food_expense

np.int64(783)

In [17]:
print("highest money spent on food on the day",highest_food_expense)

highest money spent on food on the day 783


In [19]:
avg_daily_transport = np.mean(expense_data[:,1])
avg_daily_transport

np.float64(905.4285714285714)

In [20]:
print("avg money spent on transport",avg_daily_transport)

avg money spent on transport 905.4285714285714


In [36]:
costiest_day = np.argmax(daily_totals)
costiest_day

np.int64(830)

In [28]:
print("the costiest day of the week ",costiest_day)

the costiest day of the week  9360


In [42]:
cheapest_day = np.argmin(daily_totals)
cheapest_day

np.int64(6)

In [32]:
exp_category = np.argmax(category_totals)
exp_category


np.int64(1)

In [40]:
top_3_sorted = np.argsort(daily_totals)
top_3_expdays = top_3_sorted[-3:]
top_3_expdays

array([0, 1, 2])

In [38]:
piechart = (category_totals/total_spent) * 100
piechart

array([ 8.0117355 , 47.67922967, 44.30903483])