In [22]:
import numpy as np

In [23]:
image = np.array(
    [
        [45, 120, 200, 10],
        [80, 255, 150, 60],
        [30, 90, 180, 220],
        [0, 100, 210, 250],
    ]
)

In [24]:
inverted_image = 255 - image

In [25]:
bright_image = np.clip(image+50 , 0 , 255)

In [26]:
print("original image\n" , image)

original image
 [[ 45 120 200  10]
 [ 80 255 150  60]
 [ 30  90 180 220]
 [  0 100 210 250]]


In [27]:
print( "inverted image\n ",inverted_image)

inverted image
  [[210 135  55 245]
 [175   0 105 195]
 [225 165  75  35]
 [255 155  45   5]]


In [28]:
print("bright imsge\n",bright_image)

bright imsge
 [[ 95 170 250  60]
 [130 255 200 110]
 [ 80 140 230 255]
 [ 50 150 255 255]]


In [33]:
black_and_white = np.where(image >128,255,0)
black_and_white

array([[  0,   0, 255,   0],
       [  0, 255, 255,   0],
       [  0,   0, 255, 255],
       [  0,   0, 255, 255]])

In [34]:
center_crop = image[1:3,1:3]
center_crop

array([[255, 150],
       [ 90, 180]])

In [44]:
dark_pixel_count = np.sum(image<100)
print("pixels with value less than 100",dark_pixel_count)

pixels with value less than 100 7


In [45]:
bright_pixel_count = np.sum(image>200)
print("pixels with value more than 100",bright_pixel_count)

pixels with value more than 100 4


In [37]:
avg_brightness = np.mean(image)
print("avg brightness of the image is",avg_brightness)

avg brightness of the image is 125.0


In [38]:
dark_image = np.clip(image-50,0,255)
print("dark image\n",dark_image)

dark image
 [[  0  70 150   0]
 [ 30 205 100  10]
 [  0  40 130 170]
 [  0  50 160 200]]


In [39]:
rotate_image = np.rot90(image)
print(rotate_image)
print(np.rot90(image, 2))

[[ 10  60 220 250]
 [200 150 180 210]
 [120 255  90 100]
 [ 45  80  30   0]]
[[250 210 100   0]
 [220 180  90  30]
 [ 60 150 255  80]
 [ 10 200 120  45]]


In [41]:
brightest_pixel = np.max(image)
print("Brightest pixel:", brightest_pixel)


Brightest pixel: 255


In [42]:
brightest_position = np.unravel_index(np.argmax(image), image.shape)

print("Brightest pixel:", brightest_pixel)
print("Position:", brightest_position)

Brightest pixel: 255
Position: (np.int64(1), np.int64(1))
