In [2]:
import numpy as np

In [3]:
board = np.zeros((3,3), dtype=int)
board

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
#simulate a few moves
board[0,0] = 1
board

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
board[1,1] = 1
board

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [6]:
board[2,2] = 1
board

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [7]:
board[0,1] = 2
board[1,0] = 2
print("current board state:\n" , board)

current board state:
 [[1 2 0]
 [2 1 0]
 [0 0 1]]


In [15]:
#Checking winning status for player 1
main_diag = np.diag(board)
check= np.all(main_diag == 1)
print(check)
main_diag

True


array([1, 1, 1])

In [11]:
another_diag = np.diag(np.fliplr(board))
check = np.all(another_diag==1)
print(check)
another_diag

False


array([0, 1, 0])

In [13]:
all_rows = np.all(board == 1 , axis =1)
all_rows

array([False, False, False])

In [14]:
all_columns = np.all(board == 1 , axis = 0 )
all_columns

array([False, False, False])

In [16]:
Row_0 = np.all(board[0,:]== 1)
Row_0

np.False_

In [10]:
avai_moves = np.argwhere(board == 0)
avai_moves

array([[0, 2],
       [1, 2],
       [2, 0],
       [2, 1]])

In [24]:
#Checking winning status for player 2
main_diag = np.diag(board)
main_diag
check = np.all(main_diag == 2)
check

np.False_

In [21]:
another_diag = np.diag(np.fliplr(board))
another_diag
check = np.all(another_diag==2)
check

np.False_

In [22]:
all_rows = np.all(board == 2,axis = 1)
all_rows

array([False, False, False])

In [23]:
all_columns = np.all(board == 2, axis =0)
all_columns

array([False, False, False])

In [25]:
#winner checking status
#player 1
p1_win = (
    np.all(main_diag==1)
    or np.all(another_diag==1)
    or np.any(np.all(board == 1, axis = 1))
    or np.any(np.all(board == 1 ,axis = 0))
)

In [27]:
#player 2
p2_win = (
    np.all(main_diag == 2)
    or np.all(another_diag == 2)
    or np.any(np.all(board == 2, axis = 1))
    or np.any(np.all(board == 2 ,axis = 0))
)

In [ ]:
if p1_win:
  winner = "Player 1 (X)"
elif p2_win:
  winner = "Player 2 (0)"
elif len(avai_moves) == 0:
  winner = "DRAW"
else:
  winner ="In progress"
print("Winner",winner)